### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by clemos** [clemos/try-haxe#105]
would be nice to have.

**Comment by Gama11** [comment]
Yeah, this actually made it impossible to use an embedded try.haxe snippet on the 3.4 release blog post (as that page itself uses https).

See https://github.com/HaxeFoundation/haxe.org/commit/f6a53538a443ac59fa1a2b672b39a2176636737a (cc @markknol).

**Comment by MatthijsKamstra** [comment]
it looks like bounced back to you: https://github.com/HaxeFoundation/haxe.org/issues/177#issuecomment-278564107

and I agree it would be nice to have

**Comment by clemos** [comment]
Working on it :)

**Comment by clemos** [comment]
It's done, let me know if you see any problems ;)

**Comment by clemos** [comment]
@markknol FYI I had to pull some assets from code.haxe.org to try.haxe.org because there doesn't seem to be HTTPS on code.haxe.org

**Comment by MatthijsKamstra** [comment]
It works, now I can use try safely in haxejs
![screen shot 2017-04-11 at 11 46 02](https://cloud.githubusercontent.com/assets/907219/24903068/95343aac-1eac-11e7-8766-52839313fca6.png)

thx!

**Comment by markknol** [comment]
That's good news, thanks!
