### ISSUE TITLE
Unexpected enum

### ISSUE THREAD

**Issue by tariqbenezza** [clemos/try-haxe#123]
When you try this script : 

http://try.haxe.org/#17EA8

It returns an error.

I think that I have to update the isScript method and add the `enum` keyword

**Comment by clemos** [comment]
You're right. There is also `abstract` and `typedef`

**Comment by clemos** [comment]
I already added `abstract`: https://github.com/clemos/try-haxe/blob/master/src/api/Compiler.hx#L96

**Comment by clemos** [comment]
It's not online though.
I'll release a new version tomorrow (hopefully)
