### ISSUE TITLE
interface cannot be the first declared thing

### ISSUE THREAD

**Issue by binki** [clemos/try-haxe#128]
This fails to run:

http://try.haxe.org/#29Db3

```haxe
interface IThing {}

class Thing implements IThing {
    public function new() {
    }
    public function act() {
        trace('hi');
    }
}

class Test {
    static function main() {
        new Thing();
    }
}
```

```
Test.hx:7: characters 2-11 : Unexpected interface
```

However, the following works:

http://try.haxe.org/#676ae

```haxe
class Thing implements IThing {
    public function new() {
    }
    public function act() {
        trace('hi');
    }
}

class Test {
    static function main() {
        new Thing();
    }
}

interface IThing {}
```

On my local install of haxe-3.4.0rc1 and I just installed haxe-3.3.0rc1 to verify too, both variants work.

This is confusing. If http://try.haxe.org/ fails, I’d expect the CLI compiler to fail too (when targeting JS).

**Comment by clemos** [comment]
It works now, thank for reporting :)
