### ISSUE TITLE
Invalid reg exp for splitting source to line

### ISSUE THREAD

**Issue by pleclech** [clemos/try-haxe#132]
Hello i think the regex here 
https://github.com/clemos/try-haxe/blob/master/src/SourceTools.hx#L6

is invalid as it split also the line with | and the it should split the \r\n before the other one char line.

You can see it in action here:
https://try.haxe.org/#Bdb77

Patrick.

**Comment by clemos** [comment]
Right :)
Could you please make a PR ?

**Comment by pleclech** [comment]
Done ;)

**Comment by clemos** [comment]
Your fix is online, thx :)

**Comment by pleclech** [comment]
You're welcome ;)
