### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by markknol** [clemos/try-haxe#135]
From Haxe.org repo: 

> Hi, I just wanted to test some haxe code, but it seems like try.haxe.org is not working. There is my screenshot with error in console:
> ![screen shot 2017-06-19 at 14 25 18](https://user-images.githubusercontent.com/14906262/27284997-52e8f216-54fb-11e7-9e68-8102484b5295.png)

Seems to work here, can you double check what happened?

**Comment by clemos** [comment]
Hey, 
I'm currently working out some server issues, it should be back in a few minutes.
Best,
Clément

**Comment by clemos** [comment]
maybe we should have some more robust error handling (like a nice message when the client receives such errors)

**Comment by clemos** [comment]
it's back up, sorry for the inconvenience :)
