### ISSUE TITLE
try.haxe.org is currently unusable

### ISSUE THREAD

**Issue by sjakobi** [clemos/try-haxe#144]
* The site loads super slowly
* I'm unable to load any examples
* I can't enter any code

**Comment by clemos** [comment]
That's weird, it's ok here in France.
Where are you ?

**Comment by sjakobi** [comment]
Strange, now it works again.

I wonder if the problem was caused by a HackerNews hug of death following [this submission](https://news.ycombinator.com/item?id=15961317).
