### ISSUE TITLE
Can't mention the word macro (not even in a comment or string)

### ISSUE THREAD

**Issue by ruby0x1** [clemos/try-haxe#55]
http://try.haxe.org/#e1348

edit: woops, can't link to the one mentioning it, as it rejects the code!

I simply changed to :
`"Haxe macros are great!"`

:)

**Comment by ovidiugabriel** [comment]
Yeah, not a big deal. We can just write `mac.r/o` instead, as in  [The Story of Mac](http://www.gigamonkeys.com/book/macros-defining-your-own.html). :))
