### ISSUE TITLE
Cannot test local on windows

### ISSUE THREAD

**Issue by markknol** [clemos/try-haxe#69]
I have xampp installed and have setup everything like described. Everything works, except I cannot run any program. Everything does get stored in the tmp-folder and I also can get it back using deeplinks and the embed, but when I press "build+run" it says:
```
Build failure. 
Class not found : Test
```
Any pointers on how to solve this?

**Comment by clemos** [comment]
I would guess it has to do with path separator hard-coded to `/`, for example here : https://github.com/clemos/try-haxe/blob/master/src/api/Compiler.hx#L57
You may want to replace all `/` with `haxe.io.Path.backslash ? '\' : '/'`, or even better, use the `Path` API when possible.
Unfortunately I won't have time to debug this myself, especially on Windows :p
