### ISSUE TITLE
Integrate latest haxe build 

### ISSUE THREAD

**Issue by markknol** [clemos/try-haxe#71]
This is a followup of this issue https://github.com/HaxeFoundation/haxe/issues/3745#issuecomment-69833753

Question was to add the haxe nightlys somehow on try-haxe to test snippets agains latest compiler version for comparision purposes to see if stuff breaks/is fixed.

Simn pointed me a related interesting thing that could have some more thoughts. You ask for a dev build option so we can compare manually.
But basically it would be great to automatically test the try-haxe snippets that actually compile/run. If we can log that with the current haxe version, we could compile/run the same snippets agains the latest dev build and compare the results. This would give us thousands of free tests. 
In my opinion this shouldnt be a public part of try-haxe since this is only interesting for the haxe team. I also think retesting case by case with latest devbuild is not that practical(?) but at the other hand it would be nasty to make everything complete public (who knows what people put in the snippets). So as a separate 'secret' tool/service on top of try-haxe it could be very useful.

What do you think?

**Comment by clemos** [comment]
While I think it would be nice to offer several Haxe version (for testing on latest but also/mainly so that previous snippets are garanteed to work throug time), I don't want to make try-haxe a test tool like you describe.
There are CI tools to test regressions, etc, and I don't think it's try-haxe's scope.
