### ISSUE TITLE
try.haxe.org is down

### ISSUE THREAD

**Issue by anissen** [clemos/try-haxe#73]
[haxe.org](http://haxe.org/) is up but [try.haxe.org](http://try.haxe.org/) has been down all day today :disappointed: 

![screen shot 2015-01-16 at 12 37 00](https://cloud.githubusercontent.com/assets/879967/5775621/966285e0-9d7c-11e4-91e2-91586cdb1fc1.png)

**Comment by anissen** [comment]
It's back up! :cake:

**Comment by clemos** [comment]
Yeah sorry I had to reboot my server.
Not sure what happened for now :\
