### ISSUE TITLE
 Haxe 3.2

### ISSUE THREAD

**Issue by markknol** [clemos/try-haxe#77]
Can we push the try haxe compiler along with the new 3.2 release? (Planned tomorrow)

**Comment by clemos** [comment]
Yes I'll merge all PRs and upgrade to Haxe 3.2 tomorrow.
Thanks :)

**Comment by markknol** [comment]
It would be also nice to have an option for this new static analyzer.

**Comment by clemos** [comment]
?

**Comment by markknol** [comment]
from the release notes: "Another new feature is the static analyzer which can be activated by compiling with -D analyzer. It applies various optimizations such as constant propagation and expression-level DCE which improves the quality of the generated code on targets such as Javascript. "

**Comment by anissen** [comment]
:+1: to upgrading to Haxe 3.2.0-rc.1

**Comment by clemos** [comment]
I've just upgraded to 3.2.0 rc2
Thanks !

**Comment by markknol** [comment]
Please mention the new version in the footer
