### ISSUE TITLE
Incorrect Haxe/JS translate

### ISSUE THREAD

**Issue by mikicho** [clemos/try-haxe#88]
Hi,
I came across strange issue, when I run [this] (http://try.haxe.org/#1beb8), I get this line:
> TypeError: Test.v is undefined,http://try.haxe.org/program/A461B/run?r=0.8258927006788424,line:26

But when I click on "JS Source" it's don't have line 26! 0_0
I tried to compile it on my computer and this work fine.
Thanks you on this great tool!
Miki
p.s: sorry for my lame english :)

**Comment by markknol** [comment]
You need to click on the error to see where line 26 is referring to (it is a runtime error, not directly related to the source), that will lead you to this:

![capture](https://cloud.githubusercontent.com/assets/576184/8256492/bb751786-16a7-11e5-95c1-44826e583f6b.JPG)

> In case you want to fix the error;
> you forgot to use `static var v:DynamicAccess<String> = new  DynamicAccess<String>();`

**Comment by mikicho** [comment]
oops, thanks!
