### ISSUE TITLE
Travis CI fails

### ISSUE THREAD

**Issue by clemos** [clemos/try-haxe#95]
@Gama11 any idea why travis tests keep failing ?
it seems there's a problem with the cpp target
https://travis-ci.org/clemos/try-haxe/jobs/114457550

**Comment by Gama11** [comment]
Hm, seems to only be an issue on Haxe dev. The tests of the HaxeManual are failing with the same error: https://travis-ci.org/HaxeFoundation/HaxeManual/jobs/114366732. Perhaps a recent regression.

**Comment by clemos** [comment]
Would it be possible to test the examples against the latest release version ?
Or even better, against the version currently online (3.2.0 apparently).

**Comment by Gama11** [comment]
Already happening, we test both 3.2.0 and dev: https://github.com/clemos/try-haxe/blob/master/.travis.yml#L4-L5

**Comment by Gama11** [comment]
Seems like this is simply happening because the haxelib release of hxcpp became incomaptible with Haxe dev at some point. Should work with hxcpp from git..

**Comment by clemos** [comment]
I think I'll disable development; what do you think ?

**Comment by Gama11** [comment]
Your call. I'm thinking about a way to conditionalize the hxcpp installation based on the Haxe version, which is gonna be needed for the HaxeManual either way..

**Comment by clemos** [comment]
I agree, it would make sense to pull `hxcpp` and all from git when testing `development`.
In any case, I don't think `try-haxe`'s CI should bother with Haxe/dev, so I'll just disable it.
Thanks for you insights :)

**Comment by clemos** [comment]
the green is back :)
