### ISSUE TITLE
try.haxe.org -> Examples in menu fail to build

### ISSUE THREAD

**Issue by bradparks** [clemos/try-haxe#98]
Note: I originally posted this issue in the haxe repo by accident:
https://github.com/HaxeFoundation/haxe/issues/5003

Examples seem to fail after running a WebGL example.

Here's how to duplicate it
- Go here (linked from Justin Front email, pic attached): http://try.haxe.org/#Dc3f2
- Click "Build and Run" - it works
- Click "Examples | Drawing" 
- Click "Build and Run" - it fails with the message above

Here's a pic of Justin's email
![image](https://cloud.githubusercontent.com/assets/185477/14174495/0439d796-f71b-11e5-9508-d86625e2e733.png)

**Comment by clemos** [comment]
Thanks for the report :)
This is because Justin's snippet sets main class to `Main` while our examples sets main class to `Test`.
We need to update the main class input when loading an example.

**Comment by bradparks** [comment]
Sounds good.. more FYI than anything... thanks!

**Comment by clemos** [comment]
It's mainly for me to remember what to fix (or for someone else to make a PR) :)
